ALTER TABLE HocPhan
ADD COLUMN IF NOT EXISTS SoTC INT NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS SucChua INT NOT NULL DEFAULT 40;

-- Update existing records with some default values
UPDATE HocPhan SET SoTC = 3 WHERE SoTC IS NULL;
UPDATE HocPhan SET SucChua = 40 WHERE SucChua IS NULL;
